### ISSUE TITLE
403 Forbidden on seqr-reference-data

### ISSUE THREAD

**Issue by ssadedin** [macarthur-lab/seqr#1027]
**Describe the bug**

I am trying to run the SeqR hail pipeline to import data into SeqR, but I keep getting the error below which seems to suggest that the JSON key bundled might not have access any more to the public data sets used in the pipeline?

I'm actually not sure if it could be something strange about my setup - I am running Hail from within a google cloud instance which I auth'd to my account so I don't know if there is an interaction there that could be part of the problem. However since I haven't been able to figure this out after quite a lot of trying, I was wondering if @bw2 or @hanars could confirm those resources should still be available and that service account is still configured?

Error output:

```
2019-09-14 14:03:37,836 INFO     Callset stats:
[Stage 7:=====================================================>(997 + 3) / 1000]Summary(samples=16, variants=113412, call_rate=0.772339, contigs=['X', '12', '8', '19', '4', '15', '11', '9', 'Y', '22', '13', '16', '5', '10', '21', '6', '1', '17', '14', '20', '2', '18', '7', '3'], multiallelics=0, snps=104575, mnps=0, insertions=3461, deletions=5376, complex=0, star=0, max_alleles=2)
2019-09-14 14:04:24,008 INFO     
==> total variants: 113412
2019-09-14 14:04:24,009 INFO     
==> validating vds genome_version=37 and sample_type=WES
Traceback (most recent call last):
  File "/home/simon.sadedin/seqr/hail_elasticsearch_pipelines/hail_scripts/v01/load_dataset_to_es.py", line 900, in <module>
    run_pipeline()
  File "/home/simon.sadedin/seqr/hail_elasticsearch_pipelines/hail_scripts/v01/load_dataset_to_es.py", line 867, in run_pipeline
    hc, vds = step0_init_and_run_vep(hc, vds, args)
  File "/home/simon.sadedin/seqr/hail_elasticsearch_pipelines/hail_scripts/v01/load_dataset_to_es.py", line 162, in wrapper
    result = f(*args, **kwargs)
  File "/home/simon.sadedin/seqr/hail_elasticsearch_pipelines/hail_scripts/v01/load_dataset_to_es.py", line 422, in step0_init_and_run_vep
    validate_dataset(hc, vds, args)
  File "/home/simon.sadedin/seqr/hail_elasticsearch_pipelines/hail_scripts/v01/load_dataset_to_es.py", line 323, in validate_dataset
    validate_vds_genome_version_and_sample_type(hc, vds, args.genome_version, args.sample_type)
  File "/home/simon.sadedin/seqr/hail_elasticsearch_pipelines/hail_scripts/v01/utils/validate_vds.py", line 43, in validate_vds_genome_version_and_sample_type
    gnomad_coding_variants_kt = _read_common_gnomad_variants(hail_context, genome_version, "coding")
  File "/home/simon.sadedin/seqr/hail_elasticsearch_pipelines/hail_scripts/v01/utils/validate_vds.py", line 26, in _read_common_gnomad_variants
    return hail_context.read_table(VALIDATION_KEYTABLE_PATHS[coding_or_noncoding+"_"+genome_version])
  File "<decorator-gen-517>", line 2, in read_table
  File "/home/simon.sadedin/seqr/hail_elasticsearch_pipelines/hail_builds/v01/hail-v01-10-8-2018-90c855449.zip/hail/java.py", line 121, in handle_py4j
hail.java.FatalError: GoogleJsonResponseException: 403 Forbidden
{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
    "message" : "service-account@upheld-rookery-214823.iam.gserviceaccount.com does not have storage.buckets.get access to seqr-reference-data.",
    "reason" : "forbidden"
  } ],
  "message" : "service-account@upheld-rookery-214823.iam.gserviceaccount.com does not have storage.buckets.get access to seqr-reference-data."
}
```

**Scope of the bug**

I can't import the example project after following the install steps described in the README. Everything else seems to be working (can log into SeqR, all the expected pods are running etc).

**Comment by ssadedin** [comment]
A bit more experimenting and I have realised I can in fact list the bucket with my normal credentials:

```
gsutil ls gs://seqr-reference-data/
gs://seqr-reference-data/1807_phenotype.tar.gz
gs://seqr-reference-data/gene_reference_data_backup.gz
gs://seqr-reference-data/gene_symbol_to_ensembl_id_map.txt
gs://seqr-reference-data/seqr-resource-bundle.tar.gz
gs://seqr-reference-data/GRCh37/
gs://seqr-reference-data/GRCh38/
gs://seqr-reference-data/dbnsfp/
gs://seqr-reference-data/gene_constraint/
gs://seqr-reference-data/gnomad_coverage/
gs://seqr-reference-data/gtex/
gs://seqr-reference-data/omim/
gs://seqr-reference-data/primate_ai/
gs://seqr-reference-data/test-projects/
```

So it definitely still exists and I guess must be public. So the problem would have to be with the service account if that is possible. Or something about my own setup causing it.

**Comment by ssadedin** [comment]
Tiny bit more info though it only confuses me more....

I explicitly added the stated permissions to a service account, generated a key and put that into the core-site.xml file for the Spark distribution. This produced the same error for the new account:

```
{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
    "message" : "XXXXXXX-XXXXXX@developer.gserviceaccount.com does not have storage.buckets.get access to seqr-reference-data.",
    "reason" : "forbidden"
  } ],
  "message" : "XXXXXXXX-XXXXXXX@developer.gserviceaccount.com does not have storage.buckets.get access to seqr-reference-data."
}
```

So  I am really scratching my head about it now - I feel like this problem has to be on my end, but can't explain it - any tips much appreciated!

**Comment by ssadedin** [comment]
Just posting followup after some back channel chats with @bw2 - after adding legacy read permissions to the bucket I am not experiencing this problem any more. Thanks @bw2!
