### ISSUE TITLE
Python requirements.txt versions

### ISSUE THREAD

**Issue by rsolano1-uw** [macarthur-lab/seqr#1173]
**Describe the bug**
In the requirements.txt for the seqr pipeline, two Python packages are unsuccessfully installed. Those two packages are 'openpyxl' and 'psycopg2'. Attempting to install these packages with pip at the versions listed result in errors, pasted at the bottom of this message.
 - OS: CenOS 7.7
 - Python: 2.7.5
 - Pip: 20.0.2
 - seqr pipeline: github master

I was able to install something by using the `psycopg2-binary` package for psycopg2, and the openpyxl version `2.4.1.1` instead of `2.6.4`

Are these versions sufficient for seqr to function properly?

**Link to page(s) where bug is occurring**
https://github.com/macarthur-lab/seqr/blob/master/requirements.txt

**Scope of the bug**
Installation of the seqr pipeline

**Error Output**

For psycopg2, this is the error:
```
$ pip install psycopg2==2.8.4
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting psycopg2==2.8.4
  Downloading psycopg2-2.8.4.tar.gz (377 kB)
     |################################| 377 kB 28.4 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-67aY_k/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-67aY_k/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-67aY_k/psycopg2/pip-egg-info
         cwd: /tmp/pip-install-67aY_k/psycopg2/
    Complete output (19 lines):
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'project_urls'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-67aY_k/psycopg2/setup.py", line 611, in <module>
        'Documentation': 'http://initd.org/psycopg/docs/',
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 269, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 302, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
        return self.resolve()
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2453, in resolve
        raise ImportError(str(exc))
    ImportError: 'module' object has no attribute 'check_specifier'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

For openpyxl, this is the error:
```
$ pip install openpyxl==2.6.4
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting openpyxl==2.6.4
  Using cached openpyxl-2.6.4.tar.gz (173 kB)
    ERROR: Command errored out with exit status 1:
     command: /bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-N8YJW5/openpyxl/setup.py'"'"'; __file__='"'"'/tmp/pip-install-N8YJW5/openpyxl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-N8YJW5/openpyxl/pip-egg-info
         cwd: /tmp/pip-install-N8YJW5/openpyxl/
    Complete output (19 lines):
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'project_urls'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-N8YJW5/openpyxl/setup.py", line 79, in <module>
        'Programming Language :: Python :: 3.7',
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 269, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 302, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
        return self.resolve()
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2453, in resolve
        raise ImportError(str(exc))
    ImportError: 'module' object has no attribute 'check_specifier'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by rsolano1-uw** [comment]
Not sure if this is a bug or a support request.

**Comment by rsolano1-uw** [comment]
I have found another issue with the requirements.txt that is causing seqr not to start. Installing the (modified) requirements.txt file attempts to install `django-wsgi 1.0b1`, which can't install because it doesn't support six=1.13.0, only six=1.10.0. I downgraded six to install django-wsgi, but when I launch seqr with `seqr/start_server.sh`, I still get errors that I'm missing wsgi in `seqr_settings/gunicorn.log`:

```
[2020-02-12 13:33:08 +0000] [23196] [INFO] Starting gunicorn 19.10.0
[2020-02-12 13:33:08 +0000] [23196] [INFO] Listening at: http://0.0.0.0:8000 (23196)
[2020-02-12 13:33:08 +0000] [23196] [INFO] Using worker: sync
[2020-02-12 13:33:08 +0000] [23201] [INFO] Booting worker with pid: 23201
[2020-02-12 13:33:08 +0000] [23201] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/arbiter.py", line 586, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
ImportError: No module named wsgi
[2020-02-12 13:33:08 +0000] [23201] [INFO] Worker exiting (pid: 23201)
[2020-02-12 13:33:08 +0000] [23202] [INFO] Booting worker with pid: 23202
[2020-02-12 13:33:08 +0000] [23202] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/arbiter.py", line 586, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
ImportError: No module named wsgi
[2020-02-12 13:33:08 +0000] [23202] [INFO] Worker exiting (pid: 23202)
[2020-02-12 13:33:08 +0000] [23196] [INFO] Shutting down: Master
[2020-02-12 13:33:08 +0000] [23196] [INFO] Reason: Worker failed to boot.
```

**Comment by rsolano1-uw** [comment]
Update: I was able to get seqr to start by modifying the start_server.sh script to be:

```
SETTINGSDIR="<snipped for privacy>seqr/seqr_settings"

LOG_FILE=${SETTINGSDIR}/gunicorn.log
nohup gunicorn -w 4 -c ${SETTINGSDIR}/gunicorn_config.py wsgi:application --bind 0.0.0.0:8000 >& ${LOG_FILE} &
echo "gunicorn started in background. See ${LOG_FILE}"
```

Now I can reach seqr in the web browser on port 8000, but I could not create an account with manage.py. The first time that I tried, I got an error that lxml was too old to work with openpyxl, so I updated lxml. After that, I had to run `python manage.py migrate`, and then I could createsuperuser.

**Comment by hanars** [comment]
In general, we update dependencies in order to resolve security vulnerabilities, but older versions should still work for most packages. It sounds like you got a version of packages that worked for you - do you mind reporting that here, or putting up a branch with the changes so I can take a look?

**Comment by rsolano1-uw** [comment]
Hi @hanars, thanks for the reply. I've forked your repository and made my changes here: https://github.com/rsolano1-uw/seqr. I'm not sure if there's a better way to link that. I'm pretty new to github.

I'm not sure how the `start_server.sh` script is generated, but it also had to be modified in order to function on a local install.

**Comment by hanars** [comment]
Thanks, can you attach the modified script here?

**Comment by rsolano1-uw** [comment]
Here's the modified script:

```
SETTINGSDIR="${SEQR_DIR}/seqr_settings"

LOG_FILE=${SETTINGSDIR}/gunicorn.log
nohup gunicorn -w 4 -c ${SETTINGSDIR}/gunicorn_config.py wsgi:application --bind 0.0.0.0:8000 >& ${LOG_FILE} &
echo "gunicorn started in background. See ${LOG_FILE}"
```

**Comment by bnouyou** [comment]
Hello,

I am trying to install it. And at this step I got this error in the gunicorn.log.
Maybe you can help me.

```
[2020-03-05 13:29:21 +0000] [57957] [INFO] Starting gunicorn 19.10.0
[2020-03-05 13:29:21 +0000] [57957] [INFO] Listening at: http://0.0.0.0:8000 (57957)
[2020-03-05 13:29:21 +0000] [57957] [INFO] Using worker: sync
[2020-03-05 13:29:21 +0000] [57962] [INFO] Booting worker with pid: 57962
[2020-03-05 13:29:21 +0000] [57962] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/arbiter.py", line 586, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
ImportError: No module named wsgi
[2020-03-05 13:29:21 +0000] [57962] [INFO] Worker exiting (pid: 57962)
[2020-03-05 13:29:21 +0000] [57957] [INFO] Shutting down: Master
[2020-03-05 13:29:21 +0000] [57957] [INFO] Reason: Worker failed to boot. 
```

Thank you.

**Comment by bnouyou** [comment]
Sorry, I make the changes you posted juste before in the `start_server.sh`and now it seems working.
