### ISSUE TITLE
Error in the Web interface

### ISSUE THREAD

**Issue by bnouyou** [macarthur-lab/seqr#1364]
Hello,
I have installed Seqr on-prem. I have created a project and few families.

Yesterday I have run the command for loading a dataset, and it took few hours for the calculation. The calculation of the dataset seems ok (there is no error message in the terminal at the end) but when I go in the web interface on my browser for adding the dataset on the project, I see that there is no project anymore. 
I didn't understand why, and I go on the "Admin" Django page, and here I see that the project is still here.
I have tried to create another project and I have this error:
![image](https://user-images.githubusercontent.com/22322228/87011981-ea7e7f00-c1c8-11ea-94e6-d25c2c2518ca.png)

So, I display the logs in the docker container, and I see this:
```
2020-07-09 07:30:52,106 ERROR:  Traceback (most recent call last):
seqr_1             |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
seqr_1             |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
seqr_1             |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
seqr_1             |     return view_func(request, *args, **kwargs)
seqr_1             |   File "/seqr/seqr/views/apis/dashboard_api.py", line 31, in dashboard_page_data
seqr_1             |     projects_by_guid = _get_projects_json(request.user)
seqr_1             |   File "/seqr/seqr/views/apis/dashboard_api.py", line 44, in _get_projects_json
seqr_1             |     if not projects:
seqr_1             |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 258, in __nonzero__
seqr_1             |     return type(self).__bool__(self)
seqr_1             |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 254, in __bool__
seqr_1             |     self._fetch_all()
seqr_1             |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1121, in _fetch_all
seqr_1             |     self._result_cache = list(self._iterable_class(self))
seqr_1             |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 53, in __iter__
seqr_1             |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
seqr_1             |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
seqr_1             |     raise original_exception
seqr_1             | ProgrammingError: column seqr_project.phenotips_user_id does not exist
seqr_1             | LINE 1: ..._view_group_id", "seqr_project"."genome_version", "seqr_proj...
seqr_1             |                                                              ^

```

Do you have an idea of what's happened ?

Thank you.

**Comment by hanars** [comment]
It seems like you database and the expected database schema are out of sync. From the seqr directory, try running `python manage.py migrate seqr`

**Comment by bnouyou** [comment]
Thank you. It's working now.
