### ISSUE TITLE
Error on 'Variant Search'

### ISSUE THREAD

**Issue by bnouyou** [macarthur-lab/seqr#1467]
Hello,

I have annotated and loaded a VCF file. I have imported the dataset in Seqr. This worked without any issue.

Then, when I click on 'Variant Search', even if I put no criteria, I have this error 'fields':
![image](https://user-images.githubusercontent.com/22322228/95562814-f292c880-0a1c-11eb-8041-6c72bb53a021.png)

This is what I have in logs:
```
172.18.8.26 - - [09/Oct/2020:08:47:19 +0000] "POST /api/search/b3cb33aa1c3bf5095e6a179039634bd5?sort=xpos&page=1 HTTP/1.1" 500 1297 "http://lx165/variant_search/results/b3cb33aa1c3bf5095e6a179039634bd5?page=1&sort=xpos" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
seqr_1             | 2020-10-09 08:47:55,808 INFO:  Loaded index_metadata__others_as18d046_081020201230 from redis
seqr_1             | 2020-10-09 08:47:55,809 ERROR:  Traceback (most recent call last):
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
seqr_1             |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
seqr_1             |     return view_func(request, *args, **kwargs)
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
seqr_1             |     return view_func(*args, **kwargs)
seqr_1             |   File "/seqr/seqr/views/apis/variant_search_api.py", line 73, in query_variants_handler
seqr_1             |     variants, total_results = get_es_variants(results_model, sort=sort, page=page, num_results=per_page)
seqr_1             |   File "/seqr/seqr/utils/elasticsearch/utils.py", line 119, in get_es_variants
seqr_1             |     pathogenicity=search.get('pathogenicity'))
seqr_1             |   File "/seqr/seqr/utils/elasticsearch/es_search.py", line 255, in filter_by_annotation_and_genotype
seqr_1             |     self._filter_by_genotype(inheritance_mode, inheritance_filter, quality_filters_by_family, secondary_dataset_type)
seqr_1             |   File "/seqr/seqr/utils/elasticsearch/es_search.py", line 269, in _filter_by_genotype
seqr_1             |     index_fields = self.index_metadata[index]['fields']
seqr_1             | KeyError: 'fields'
seqr_1             |
seqr_1             | 172.18.8.26 - - [09/Oct/2020:08:47:55 +0000] "POST /api/search/b3cb33aa1c3bf5095e6a179039634bd5?sort=xpos&page=1 HTTP/1.1" 500 1297 "http://lx165/variant_search/results/b3cb33aa1c3bf5095e6a179039634bd5?page=1&sort=xpos" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
```

On other samples (annotated and loaded before) the 'Variant Search' works well.
What I have done between is pulling the last version (because of another issue with the visualization of bam files).

Thank you in advance for your help.

**Comment by hanars** [comment]
try resetting your redis cache

**Comment by bnouyou** [comment]
Thank you. This works well !
