### ISSUE TITLE
manage.py load resources error

### ISSUE THREAD

**Issue by nvteja** [macarthur-lab/seqr#451]
Hello,

I was trying to install seqr on mac by following instructions at https://github.com/macarthur-lab/seqr/tree/master/deploy/mac_osx. 

Unfortunately, I am running into an error at the Initialize step at ./manage.py load_resources command. 

Here is what I get when I run this command

2018-07-03 20:43:57,168 WARNING:  WARNING: get_reference().get_gene_symbols(): gene_symbols collection not found in mongodb. If this is a new install, please run python manage.py load_resources
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/teja/Desktop/SEQR/code/seqr/xbrowse_server/base/management/commands/load_resources.py", line 6, in handle
    get_reference().load()
  File "/Users/teja/Desktop/SEQR/code/seqr/xbrowse/reference/reference.py", line 69, in load
    self._load_clinvar()
  File "/Users/teja/Desktop/SEQR/code/seqr/xbrowse/reference/reference.py", line 140, in _load_clinvar
    chunk = list(itertools.islice(iterator, 0, 1000))
  File "/Users/teja/Desktop/SEQR/code/seqr/xbrowse/reference/clinvar.py", line 20, in parse_clinvar_vcf
    clinvar_vcf_path = settings.REFERENCE_SETTINGS.clinvar_vcf_file
AttributeError: 'module' object has no attribute 'clinvar_vcf_file'

Looks like the manage.py is unable to find the clinvar vcf file. Are there any additional resources/files that I would have to download before running the load_resources command?

Thank you,
Teja.

**Comment by nvteja** [comment]
Just to add , I have downloaded the seqr-resource-bundle as part of the instructions.

**Comment by hanars** [comment]
It looks like theres a bug in `reference_settings.py` for that deploy only includes the `clinvar_tsv_file` field. I would either update that file to have a `clinvar_vcf_file` field that references the vcf you have, or if you have a tsv and not a vcf I would update the loading script to use that instead

**Comment by naumenko-sa** [comment]
Hi @hanars !

Thanks for the suggestion!

Just for the record, I was able to pass the clinvar step:
1. I downloaded clinvar vcf and tbi from [ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh37/](clinvar). More precisely, I used ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh37/clinvar_20180701.vcf.gz.
2. I saved the files under [SEQR_INSTALL_DIR]/data/reference_data. (I renamed the files to clinvar.vcf.gz and clinvar.vcf.gz.tbi)
3. I modified [SEQR_INSTALL_DIR]/code/seqr/deploy/mac_osx/xbrowse_settings/reference_settings.py:
3.1. Removed clinvar_tsv_file line
3.2. Added 
```clinvar_vcf_file = "[absolute path to clinvar.vcf.gz]"```
Additional note: referencing clinvar.vcf.gz with REFERENCE_DATA_FILES(['clinvar']) did not work for me.

```[SEQR_INSTALL_DIR]/data/reference_data/clinvar.tsv```  is a part of SEQR data bundle. Would it be possible to use this file automatically in the installer? If not, could you please add the clinvar.vcf step to the installation instructions at https://github.com/macarthur-lab/seqr/tree/master/deploy/mac_osx?

It seems that for the new installation `./manage.py migrate` is not working unless `./manage.py load_resources` step is finished. If this is true, could you please switch them in the https://github.com/macarthur-lab/seqr/tree/master/deploy/mac_osx?

SN

**Comment by naumenko-sa** [comment]
died with 
```IOError: File [SEQR_INSTALL_DIR]/data/reference_data/constraint_scores.csv does not exist```

using gene_constraint_scores.csv does not help:
```
Traceback (most recent call last):s:  99% |-------------------------------------------------------------------------------------------------------------------------------------------------------- | ETA:  0:00:00
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib64/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib64/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/sergey/Desktop/tools/seqr/code/seqr/xbrowse_server/base/management/commands/load_resources.py", line 6, in handle
    get_reference().load()
  File "/home/sergey/Desktop/tools/seqr/code/seqr/xbrowse/reference/reference.py", line 79, in load
    self._load_tags()
  File "/home/sergey/Desktop/tools/seqr/code/seqr/xbrowse/reference/reference.py", line 231, in _load_tags
    self._load_gene_test_statistic_tags()
  File "/home/sergey/Desktop/tools/seqr/code/seqr/xbrowse/reference/reference.py", line 254, in _load_gene_test_statistic_tags
    scores = getattr(score_data, tag_field)
  File "/usr/lib64/python2.7/site-packages/pandas/core/generic.py", line 2744, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'pLI'
``` 
Could you please provide the correct constraint_scores.csv file?

**Comment by naumenko-sa** [comment]
After resolving clinvar and constraint issues, ```./manage.py load_resources``` finished successfully.

When trying 
```
./manage.py migrate
```

One of the migrations (20171112_1649) failed with:

```
ERROR: column base_project.genome_version does not exist
LINE 1: SELECT "base_project"."id", "base_project"."genome_version",...
                                    ^

Operations to perform:
  Apply all migrations: admin, auth, base, breakpoint_search, contenttypes, gene_lists, guardian, reference_data, seqr, sessions
Running migrations:
  Applying seqr.0026_auto_20171112_1649...Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib64/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib64/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/lib64/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/lib64/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/lib64/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/lib64/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/lib64/python2.7/site-packages/django/db/migrations/migration.py", line 119, in apply
    operation.state_forwards(self.app_label, project_state)
  File "/usr/lib64/python2.7/site-packages/django/db/migrations/operations/models.py", line 90, in state_forwards
    list(self.managers),
  File "/usr/lib64/python2.7/site-packages/django/db/migrations/state.py", line 93, in add_model
    self.reload_model(app_label, model_name)
  File "/usr/lib64/python2.7/site-packages/django/db/migrations/state.py", line 162, in reload_model
    self.apps.render_multiple(states_to_be_rendered)
  File "/usr/lib64/python2.7/site-packages/django/db/migrations/state.py", line 277, in render_multiple
    model.render(self)
  File "/usr/lib64/python2.7/site-packages/django/db/migrations/state.py", line 559, in render
    body,
  File "/usr/lib64/python2.7/site-packages/django/db/models/base.py", line 119, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/usr/lib64/python2.7/site-packages/django/db/models/base.py", line 316, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/lib64/python2.7/site-packages/django/db/models/options.py", line 206, in contribute_to_class
    raise TypeError("'class Meta' got invalid attribute(s): %s" % ','.join(meta_attrs.keys()))
TypeError: 'class Meta' got invalid attribute(s): indexes

```
Could you please advice how to overcome this and finish the installation?
Many thanks!
SN

**Comment by hanars** [comment]
That could be an issue with the version of django you have installed. You can run `pip freeze` to see the list of all the packages and versions you have installed and then check to make sure Django is using 1.11

**Comment by naumenko-sa** [comment]
Yes, you are right, I had 1.10.8.
With 1.11 installation finished well!

**Comment by hanars** [comment]
glad to hear it. You may also want to try running `pip install -r requiremnts.txt` again just to make sure that you have the expected version of everything else, as you may run into some other bugs if your packages differ from the specified versions
