### ISSUE TITLE
HailException: Struct has no field `gq' when loading mantasv

### ISSUE THREAD

**Issue by nvteja** [macarthur-lab/seqr#796]
Hello,

I am trying to load a vcf file with manta sv calls into seqr and I am encountering this error at the "export to elastic search - vds schema" step. I pulled the latest version of seqr and hail scripts and performed migration. 

```
Traceback (most recent call last):
  File "/home/arun/seqr/seqr/hail_elasticsearch_pipelines/hail_scripts/v01/load_dataset_to_es.py", line 900, in <module>
    run_pipeline()
  File "/home/arun/seqr/seqr/hail_elasticsearch_pipelines/hail_scripts/v01/load_dataset_to_es.py", line 869, in run_pipeline
    hc, vds = step2_export_to_elasticsearch(hc, vds, args)
  File "/home/arun/seqr/seqr/hail_elasticsearch_pipelines/hail_scripts/v01/load_dataset_to_es.py", line 162, in wrapper
    result = f(*args, **kwargs)
  File "/home/arun/seqr/seqr/hail_elasticsearch_pipelines/hail_scripts/v01/load_dataset_to_es.py", line 653, in step2_export_to_elasticsearch
    run_after_index_exists=(lambda: route_index_to_temp_es_cluster(True, args)) if args.use_temp_loading_nodes else None,
  File "/home/arun/seqr/seqr/hail_elasticsearch_pipelines/hail_scripts/v01/load_dataset_to_es.py", line 398, in export_to_elasticsearch
    force_merge=force_merge,
  File "/home/arun/seqr/seqr/hail_elasticsearch_pipelines/hail_scripts/v01/utils/elasticsearch_client.py", line 123, in export_vds_to_elasticsearch
    vds = _add_vds_sample_field(vds, field_name='gq_{}_to_{}'.format(i, i + 5), field_filter='gen.gq >= {0} && gen.gq < {0} + 5'.format(i))
  File "/home/arun/seqr/seqr/hail_elasticsearch_pipelines/hail_scripts/v01/utils/elasticsearch_client.py", line 115, in _add_vds_sample_field
    field_name=field_name, field_filter=field_filter
  File "<decorator-gen-250>", line 2, in annotate_variants_expr
  File "/home/arun/seqr/seqr/hail_elasticsearch_pipelines/hail_builds/v01/hail-v01-10-8-2018-90c855449.zip/hail/java.py", line 121, in handle_py4j
hail.java.FatalError: HailException: Struct has no field `gq'
  Available fields:
    dp_SR: Int
    ab_SR: Float
    ab: Float
    dp_PR: Int
    num_alt: Int
    ab_PR: Float
    dp: Int
    sample_id: String
<input>:1:va.samples_gq_0_to_5 = va.genotypes.filter(gen => gen.gq >= 0 && gen.gq < 0 + 5).map(gen => gen.sample_id).toSet
                                                               ^
Java stack trace:
is.hail.utils.HailException: Struct has no field `gq'
  Available fields:
    dp_SR: Int
    ab_SR: Float
    ab: Float
    dp_PR: Int
    num_alt: Int
    ab_PR: Float
    dp: Int
    sample_id: String
<input>:1:va.samples_gq_0_to_5 = va.genotypes.filter(gen => gen.gq >= 0 && gen.gq < 0 + 5).map(gen => gen.sample_id).toSet

Hail version: 0.1-105a497
Error summary: HailException: Struct has no field `gq'
  Available fields:
    dp_SR: Int
    ab_SR: Float
    ab: Float
    dp_PR: Int
    num_alt: Int
    ab_PR: Float
    dp: Int
    sample_id: String
<input>:1:va.samples_gq_0_to_5 = va.genotypes.filter(gen => gen.gq >= 0 && gen.gq < 0 + 5).map(gen => gen.sample_id).toSet
                                                               ^
/home/arun/seqr/seqr/../bin/spark-2.0.2-bin-hadoop2.7/bin/spark-submit                  --driver-memory 5G         --executor-memory 5G         --num-executors 2         --conf spark.driver.extraJavaOptions=-Xss4M         --conf spark.executor.extraJavaOptions=-Xss4M         --conf spark.executor.memoryOverhead=5g         --conf spark.driver.maxResultSize=30g         --conf spark.kryoserializer.buffer.max=1g         --conf spark.memory.fraction=0.1         --conf spark.default.parallelism=1         --jars hail_builds/v01/hail-v01-10-8-2018-90c855449.jar         --conf spark.driver.extraClassPath=hail_builds/v01/hail-v01-10-8-2018-90c855449.jar         --conf spark.executor.extraClassPath=hail_builds/v01/hail-v01-10-8-2018-90c855449.jar         --py-files hail_builds/v01/hail-v01-10-8-2018-90c855449.zip         "hail_scripts/v01/load_dataset_to_es.py" "--genome-version" "37" "--project-guid" "R0013_1074_ch0164_sv" "--sample-type" "WGS" "--dataset-type" "SV" "--skip-validation" "--exclude-hgmd" "--vep-block-size" "100" "--es-block-size" "10" "--num-shards" "1" "--use-nested-objects-for-vep" "--use-nested-objects-for-genotypes" "/home/arun/seqr_data/CH0164SV.vcf.gz" --username 'arun' --directory 'seqr-dev-32:/home/arun/seqr/seqr/hail_elasticsearch_pipelines
```

Could you please advise on how to proceed ?

Thanks,
Teja.

**Comment by bw2** [comment]
@nvteja  Just so I can confirm, what was your command line?   

@hanars would it work to load without --nested-genotypes?

**Comment by nvteja** [comment]
Here.  Thank you!

```
cd ${SEQR_DIR}/hail_elasticsearch_pipelines/
GENOME_VERSION="37"        # should be "37" or "38"
SAMPLE_TYPE="WGS"          # can be "WES" or "WGS"
DATASET_TYPE="SV"    # can be "VARIANTS" (for GATK VCFs) or "SV" (for Manta VCFs)
PROJECT_GUID="R0013_1074_ch0164_sv"   # should match the ID in the url of the project page 
INPUT_VCF="CH0164SV.vcf.gz"    # local path of VCF file
python2.7 gcloud_dataproc/submit.py --run-locally hail_scripts/v01/load_dataset_to_es.py --spark-home $SPARK_HOME --genome-version $GENOME_VERSION --project-guid $PROJECT_GUID --sample-type $SAMPLE_TYPE --dataset-type $DATASET_TYPE --skip-validation  --exclude-hgmd --vep-block-size 100 --es-block-size 10 --num-shards 1 --hail-version 0.1 --use-nested-objects-for-vep --use-nested-objects-for-genotypes $INPUT_VCF

```

**Comment by hanars** [comment]
SVs are not supported for nested genotypes. You should instead run:
`python2.7 gcloud_dataproc/submit.py --run-locally hail_scripts/v01/load_dataset_to_es.py --spark-home $SPARK_HOME --genome-version $GENOME_VERSION --project-guid $PROJECT_GUID --sample-type $SAMPLE_TYPE --dataset-type $DATASET_TYPE --skip-validation  --exclude-hgmd --vep-block-size 100 --es-block-size 10 --num-shards 1 --hail-version 0.1  $INPUT_VCF`

**Comment by nvteja** [comment]
> SVs are not supported for nested genotypes. You should instead run:
> `python2.7 gcloud_dataproc/submit.py --run-locally hail_scripts/v01/load_dataset_to_es.py --spark-home $SPARK_HOME --genome-version $GENOME_VERSION --project-guid $PROJECT_GUID --sample-type $SAMPLE_TYPE --dataset-type $DATASET_TYPE --skip-validation --exclude-hgmd --vep-block-size 100 --es-block-size 10 --num-shards 1 --hail-version 0.1 $INPUT_VCF`

This works! Thank you so much @hanars and @bw2 !
