### ISSUE TITLE
manage.py update_omim is broken

### ISSUE THREAD

**Issue by bw2** [macarthur-lab/seqr#880]
Running 
```
python -u manage.py update_omim --omim-key $OMIM_KEY
```
terminates with 
```
2019-05-28 19:58:59,966 INFO:  Parsing file
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/seqr/reference_data/management/commands/utils/update_utils.py", line 62, in handle
    update_records(self.reference_data_handler(**options), file_path=options.get('file_path'), )
  File "/seqr/reference_data/management/commands/utils/update_utils.py", line 89, in update_records
    header_fields = reference_data_handler.get_file_header(f)
  File "/seqr/reference_data/management/commands/update_omim.py", line 94, in get_file_header
    raise ValueError("Header row not found in genemap2 file before line {}: {}".format(i, line))
NameError: global name 'i' is not defined
```

**Comment by hanars** [comment]
This is because our OMIM key expired (although there is a bug thats preventing this from showing a useful error message). I'll reactivate it
