### ISSUE TITLE
validate_index_metadata(..) fails for local dataset paths

### ISSUE THREAD

**Issue by bw2** [macarthur-lab/seqr#891]
`validate_index_metadata(..)` fails on local datasets because the working directory is different from the loading script directory.

```
2019-06-09 17:30:09,723 INFO:  GET http://localhost:9200/r001_test__wes__grch37__variants__20190607/_search?size=0 [status:200 request:0.030s]
Traceback (most recent call last):
  File "/home/test/seqr/seqr/views/apis/dataset_api.py", line 57, in add_variants_dataset_handler
    validate_index_metadata(index_metadata, project, elasticsearch_index)
  File "/home/test/seqr/seqr/views/utils/dataset_utils.py", line 46, in validate_index_metadata
    _validate_vcf_metadata(dataset_path)
  File "/home/test/seqr/seqr/views/utils/dataset_utils.py", line 96, in _validate_vcf_metadata
    metadata = '\n'.join([line for line in file_utils.file_iter(vcf_path)])
  File "/home/test/seqr/seqr/utils/file_utils.py", line 27, in file_iter
    with open(file_path) as f:
IOError: [Errno 2] No such file or directory: u'1kg.vep.vds/metadata.json.gz'
```

We should make local paths absolute before saving them, and/or disable this validation step for local paths.

**Comment by hanars** [comment]
Honestly I was on the fence about validating the source file itself anyways because its kind of slow, so I'm just going to get rid of it entirely
